---
- name: Install python packages
  pip:
    name: requests
    state: present
    executable: pip3
  tags:
    monitoring.script

- name: Create script folder
  file:
    path: "{{ node.solana_home }}/monitoring"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0755
    state: directory
  tags: 
    monitoring.script

- name: Upload monitoring library
  copy:
    src: files/validator_monitoring_library.py
    dest: "{{ node.solana_home }}/monitoring/validator_monitoring_library.py"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0644
  tags:
    monitoring.script

- name: Upload common
  copy:
    src: files/common.py
    dest: "{{ node.solana_home }}/monitoring/common.py"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0644
  tags:
    monitoring.script

- name: Upload request_utils
  copy:
    src: files/request_utils.py
    dest: "{{ node.solana_home }}/monitoring/request_utils.py"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0644
  tags:
    monitoring.script

- name: Upload solana_rpc
  copy:
    src: files/solana_rpc.py
    dest: "{{ node.solana_home }}/monitoring/solana_rpc.py"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0644
  tags:
    monitoring.script

- name: Upload monitoring script
  template:
    src: validator_monitoring.py.j2
    dest: "{{ node.solana_home }}/monitoring/validator_monitoring.py"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0755
  tags: 
    monitoring.script
  
