---
  - name: Build solana cli
    import_tasks: install_packages.yaml
    tags:
      - cli
      - cli.packages


  - name: Download sources
    import_tasks: get_sources.yaml
    tags:
      - cli
      - cli.sources

  - name: Build release
    import_tasks: build_release.yaml
    tags:
      - cli
      - cli.build

