---
all:
  children:
    local:
      hosts:
        local_server:
          become: false
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
          solana_user: root
    remote:
      vars:
        ansible_user: root
      children:
        validator:
          vars:
            validator_name:
#            keybase_username: ""
#            validator_homepage: ""
#            upload_validator_keys: False
#            secrets_path: /home/solana/.secrets
#            set_validator_info: True
#            service_user: solana
#            ledger_path: /home/solana/ledger
#            lvm_enabled: False
#            lvm_vg: vg00
#            solana_validator_service: restarted
#            swap_file_size_gb: 64
#            ramdisk_size_gb: 64
#            cluster_environment: testnet
#            cluster_rpc_address: https://api.testnet.solana.com
          hosts:
            0.0.0.0
